volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: 
      - /home/yc-user/envs/kittygram.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: lichnyy/kittygram_backend:latest  
    env_file: 
      - /home/yc-user/envs/kittygram.env
    volumes:
      - static_volume:/backend_static/
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: lichnyy/kittygram_frontend:latest 
    env_file:
       - /home/yc-user/envs/kittygram.env 
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend

  gateway:
    image: lichnyy/kittygram_gateway:latest  
    env_file: 
      - /home/yc-user/envs/kittygram.env
    volumes:
      - static_volume:/static/
      - media:/app/media/
    ports:
      - 9000:80
    depends_on:
      - frontend
