# name: Kittygram CI/CD

# on:
#   push:
#     branches:
#        - '**'
#   pull_request:     

# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ['3.9', '3.10', '3.11']    
#     services:
#       postgres:      
#         image: postgres:13.10
#         env:
#           POSTGRES_USER: kittygram_user
#           POSTGRES_PASSWORD: your_secure_password_123
#           POSTGRES_DB: kittygram
#         ports:
#           - 5432:5432
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Install system dependencies
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y libjpeg-dev zlib1g-dev libtiff5-dev libopenjp2-7-dev libfreetype6-dev

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip setuptools
#         pip install flake8==6.0.0 flake8-isort==6.0.0
#         pip install -r ./backend/requirements.txt 
#     - name: Test with flake8 and django tests
#       env:
#         POSTGRES_USER: kittygram_user
#         POSTGRES_PASSWORD: your_secure_password_123
#         POSTGRES_DB: kittygram
#         SECRET_KEY: ${{ secrets.SECRET_KEY }}
#         DB_HOST: 127.0.0.1
#         DB_PORT: 5432
#       run: |
#         python -m flake8 backend/
#         cd backend/
#         python manage.py test
          

#   frontend_tests:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up nodeJS
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18
#     - name: Install dependencies
#       run: |
#         cd frontend/
#         npm ci
#     - name: Test frontend
#       run: |
#         cd frontend/
#         npm run test

#   build_and_push_to_docker_hub:
#     name: Push backend Docker image to DockerHub
#     runs-on: ubuntu-latest
#     needs: tests
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker 
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Push to DockerHub
#         uses: docker/build-push-action@v4
#         with:
#           context: ./backend/
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest

#   build_frontend_and_push_to_docker_hub:
#     name: Push frontend Docker image to DockerHub
#     runs-on: ubuntu-latest
#     needs: frontend_tests
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker 
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Push to DockerHub
#         uses: docker/build-push-action@v4
#         with:
#           context: ./frontend/
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest

#   build_gateway_and_push_to_docker_hub:
#     name: Push gateway Docker image to DockerHub
#     runs-on: ubuntu-latest
#     needs: tests 
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker 
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Push to DockerHub
#         uses: docker/build-push-action@v4
#         with:
#           context: ./nginx/
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: 
#       - build_and_push_to_docker_hub
#       - build_frontend_and_push_to_docker_hub
#       - build_gateway_and_push_to_docker_hub
#     steps:
             
#       - name: Checkout repo
#         uses: actions/checkout@v3
      
#       - name: Create .env on server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_KEY }}          
#           script: |
#             # СОЗДАЕМ ДИРЕКТОРИЮ С ПРАВИЛЬНЫМ ПУТЕМ
#             sudo mkdir -p /home/yc-user/envs
#             sudo chown ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} /home/yc-user/envs
            
#             cat << 'EOF' > /home/yc-user/envs/kittygram.env            
#             POSTGRES_USER=kittygram_user
#             POSTGRES_PASSWORD=your_secure_password_123
#             DB_HOST=db
#             DB_PORT=5432
#             DEBUG=True
#             SECRET_KEY=${{ secrets.SECRET_KEY }}
#             ALLOWED_HOSTS=localhost,127.0.0.1,158.160.195.202,backend,gateway
#             EOF
#             chmod 600 /home/yc-user/envs/kittygram.env

#       - name: Copy docker-compose.production.yml to server
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           source: "docker-compose.production.yml"
#           target: "kittygram"             
#           debug: true
     
#       - name: Deploy application
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             cd kittygram
#             sudo docker compose -f docker-compose.production.yml pull
#             sudo docker compose -f docker-compose.production.yml down
#             sudo docker compose -f docker-compose.production.yml up -d
#             sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
#             sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --noinput
#             sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /backend_static/static/ 
    
#   send_message:
#     runs-on: ubuntu-latest
    
#     needs: deploy
#     steps:        
#       - name: Send Telegram notification
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_CHAT_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           message: |
#             ✅ Kittygram успешно задеплоен!
#              Автор: ${{ github.actor }}
#              Коммит: ${{ github.event.commits[0].message }}
#              Ссылка: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


name: Test SSH Connection
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: echo "SSH подключение успешно!!"